# -*- coding: utf-8 -*-
"""htmlgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7GOu3WoL1hXvZcKo_0AOgUfdfyk7mNJ

Install Dependencies
"""

# Install Gradio UI framework
!pip install -q gradio

# Install HuggingFace Transformers for AI models
!pip install -q transformers

# Install Accelerate for optimized model loading
!pip install -q accelerate

# Install PyTorch (Deep Learning backend)
!pip install -q torch

# Install HuggingFace Hub for downloading models
!pip install -q huggingface_hub

print("✅ All dependencies installed successfully!")

"""Import Libraries"""

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import json
import os
import random
import re
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


print("✅ Libraries imported successfully!")
print(f"⚙️ Running on device: {DEVICE}")

print("✅ Libraries imported successfully!")

"""Load IBM Granite Model"""

print("⏳ Loading IBM Granite model...")

MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto"
)

print("✅ Granite model loaded successfully!")

"""AI HTML Generator"""

def generate_content(prompt):

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.6,
        top_p=0.9,
        do_sample=True
    )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text

"""Template Engine"""

class TemplateEngine:

    def __init__(self):

        # ---------------------------------
        # Template Input Fields
        # ---------------------------------
        self.templates = {

            "Portfolio Website": [
                "Your Name",
                "About You",
                "Skills",
                "Projects",
                "Contact Email"
            ],

            "SaaS Landing Page": [
                "Product Name",
                "Product Description",
                "Main Feature",
                "Second Feature",
                "Pricing Plan"
            ],

            "Corporate Website": [
                "Company Name",
                "Company Mission",
                "Services",
                "Team Description",
                "Contact Info"
            ],

            "Restaurant Website": [
                "Restaurant Name",
                "About Restaurant",
                "Popular Dish",
                "Location",
                "Contact Number"
            ],

            "Personal Blog": [
                "Blog Name",
                "About Author",
                "Main Topic",
                "Latest Post Title",
                "Contact Email"
            ]

        }

    # ---------------------------------
    # Get template list
    # ---------------------------------
    def list_templates(self):
        return list(self.templates.keys())

    # ---------------------------------
    # Get template fields
    # ---------------------------------
    def get_fields(self, template_name):
        return self.templates.get(template_name, [])


# Create engine instance
template_engine = TemplateEngine()

print("✅ Template Engine Ready")
print("Available Templates:")
print(template_engine.list_templates())

"""HTML Templates System"""

class HTMLTemplates:

    def portfolio(self, data):

        html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{data['name']} Portfolio</title>
</head>

<body>

<nav>
<h2>{data['name']}</h2>
</nav>

<section class="hero">
<h1>Hello I'm {data['name']}</h1>
<p>{data['hero_text']}</p>
</section>

<section class="about">
<h2>About Me</h2>
<p>{data['about']}</p>
</section>

<section class="skills">
<h2>Skills</h2>
<p>{data['skills']}</p>
</section>

<section class="projects">
<h2>Projects</h2>
<p>{data['projects']}</p>
</section>

<footer>
<p>Contact: {data['email']}</p>
</footer>

</body>
</html>
"""
        return html


    def saas(self, data):

        html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{data['product']} Landing Page</title>
</head>

<body>

<section class="hero">
<h1>{data['product']}</h1>
<p>{data['hero_text']}</p>
</section>

<section class="features">
<h2>Features</h2>
<ul>
<li>{data['feature1']}</li>
<li>{data['feature2']}</li>
</ul>
</section>

<section class="pricing">
<h2>Pricing</h2>
<p>{data['pricing']}</p>
</section>

<footer>
<p>© {data['product']} 2026</p>
</footer>

</body>
</html>
"""
        return html


    def corporate(self, data):

        html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{data['company']}</title>
</head>

<body>

<header>
<h1>{data['company']}</h1>
</header>

<section>
<h2>Mission</h2>
<p>{data['mission']}</p>
</section>

<section>
<h2>Services</h2>
<p>{data['services']}</p>
</section>

<section>
<h2>Team</h2>
<p>{data['team']}</p>
</section>

<footer>
<p>{data['contact']}</p>
</footer>

</body>
</html>
"""
        return html


    def restaurant(self, data):

        html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{data['restaurant']}</title>
</head>

<body>

<section class="hero">
<h1>{data['restaurant']}</h1>
<p>{data['hero_text']}</p>
</section>

<section>
<h2>About</h2>
<p>{data['about']}</p>
</section>

<section>
<h2>Popular Dish</h2>
<p>{data['dish']}</p>
</section>

<footer>
<p>{data['location']} | {data['phone']}</p>
</footer>

</body>
</html>
"""
        return html


    def blog(self, data):

        html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{data['blog']}</title>
</head>

<body>

<header>
<h1>{data['blog']}</h1>
</header>

<section>
<h2>About Author</h2>
<p>{data['about']}</p>
</section>

<section>
<h2>Latest Post</h2>
<h3>{data['post']}</h3>
<p>{data['post_text']}</p>
</section>

<footer>
<p>Contact: {data['email']}</p>
</footer>

</body>
</html>
"""
        return html


# Create template object
html_templates = HTMLTemplates()

print("✅ HTML Templates Ready")

"""Color Palette Generator"""

class ColorPalette:

    def __init__(self):

        self.palettes = {

            "modern": {
                "primary": "#2563EB",
                "secondary": "#4F46E5",
                "background": "#F8FAFC",
                "text": "#111827"
            },

            "vibrant": {
                "primary": "#FF3B3B",
                "secondary": "#FF8C00",
                "background": "#FFF7ED",
                "text": "#1F2937"
            },

            "ocean": {
                "primary": "#0284C7",
                "secondary": "#0369A1",
                "background": "#F0F9FF",
                "text": "#0F172A"
            },

            "forest": {
                "primary": "#166534",
                "secondary": "#15803D",
                "background": "#F0FDF4",
                "text": "#052E16"
            },

            "sunset": {
                "primary": "#F97316",
                "secondary": "#FB923C",
                "background": "#FFF7ED",
                "text": "#1F2937"
            },

            "luxury": {
                "primary": "#111827",
                "secondary": "#374151",
                "background": "#F9FAFB",
                "text": "#111827"
            },

            "creative": {
                "primary": "#7C3AED",
                "secondary": "#9333EA",
                "background": "#FAF5FF",
                "text": "#1F2937"
            },

            "minimal": {
                "primary": "#111111",
                "secondary": "#444444",
                "background": "#FFFFFF",
                "text": "#111111"
            }

        }

    def get_palette(self, name):
        return self.palettes.get(name, self.palettes["modern"])

    def list_palettes(self):
        return list(self.palettes.keys())


palette_engine = ColorPalette()

print("✅ Color Palette Engine Ready")
print("Available palettes:", palette_engine.list_palettes())

"""CSS Generator"""

def generate_css(palette):

    css = f"""
<style>

body {{
font-family: Arial, sans-serif;
margin:0;
padding:0;
background:{palette['background']};
color:{palette['text']};
}}

nav {{
background:{palette['primary']};
color:white;
padding:15px;
}}

.hero {{
background:linear-gradient(135deg,{palette['primary']},{palette['secondary']});
color:white;
padding:80px 20px;
text-align:center;
}}

section {{
padding:40px;
max-width:1000px;
margin:auto;
}}

footer {{
background:{palette['primary']};
color:white;
text-align:center;
padding:20px;
margin-top:40px;
}}

button {{
background:{palette['secondary']};
color:white;
border:none;
padding:10px 20px;
border-radius:6px;
cursor:pointer;
}}

button:hover {{
opacity:0.9;
}}

</style>
"""
    return css

print("🎨 CSS Generator Ready")

"""Website Generator Pipeline"""

def generate_website(template_name, palette_name, inputs):

    # ---------------------------------
    # 1 Get selected palette
    # ---------------------------------
    palette = palette_engine.get_palette(palette_name)

    css = generate_css(palette)

    # ---------------------------------
    # 2 Generate AI content
    # ---------------------------------
    prompt = f"""
Generate short professional website text.

Template: {template_name}

User Data:
{inputs}

Write:
Hero section text
About section text
Short description text
"""

    ai_text = generate_content(prompt)

    # ---------------------------------
    # 3 Prepare template data
    # ---------------------------------

    data = {}

    if template_name == "Portfolio Website":

        data = {
            "name": inputs[0],
            "hero_text": ai_text,
            "about": inputs[1],
            "skills": inputs[2],
            "projects": inputs[3],
            "email": inputs[4]
        }

        html = html_templates.portfolio(data)


    elif template_name == "SaaS Landing Page":

        data = {
            "product": inputs[0],
            "hero_text": ai_text,
            "feature1": inputs[2],
            "feature2": inputs[3],
            "pricing": inputs[4]
        }

        html = html_templates.saas(data)


    elif template_name == "Corporate Website":

        data = {
            "company": inputs[0],
            "mission": inputs[1],
            "services": inputs[2],
            "team": inputs[3],
            "contact": inputs[4]
        }

        html = html_templates.corporate(data)


    elif template_name == "Restaurant Website":

        data = {
            "restaurant": inputs[0],
            "hero_text": ai_text,
            "about": inputs[1],
            "dish": inputs[2],
            "location": inputs[3],
            "phone": inputs[4]
        }

        html = html_templates.restaurant(data)


    elif template_name == "Personal Blog":

        data = {
            "blog": inputs[0],
            "about": inputs[1],
            "post": inputs[3],
            "post_text": ai_text,
            "email": inputs[4]
        }

        html = html_templates.blog(data)

    # ---------------------------------
    # 4 Insert CSS
    # ---------------------------------

    final_html = html.replace(
        "<head>",
        f"<head>\n{css}"
    )

    # ---------------------------------
    # 5 Save HTML file
    # ---------------------------------

    file_path = "generated_website.html"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(final_html)

    return final_html, file_path


print("🚀 Website Generator Engine Ready")

"""Gradio Interface"""

import gradio as gr


# ------------------------------
# Generate Button Function
# ------------------------------

def ui_generate(template, palette, name, about, field3, field4, field5):

    inputs = [name, about, field3, field4, field5]

    html, file_path = generate_website(
        template,
        palette,
        inputs
    )

    return html, html, file_path


# ------------------------------
# Template Guide HTML
# ------------------------------

templates_html = """
<h2>Available Website Templates</h2>

<ul>
<li><b>Portfolio Website</b> – Personal developer portfolio</li>
<li><b>SaaS Landing Page</b> – Startup product page</li>
<li><b>Corporate Website</b> – Business company website</li>
<li><b>Restaurant Website</b> – Food and dining website</li>
<li><b>Personal Blog</b> – Blog and article website</li>
</ul>
"""


# ------------------------------
# Color Palette Reference
# ------------------------------

palette_html = ""

for name in palette_engine.list_palettes():

    p = palette_engine.get_palette(name)

    palette_html += f"""
    <div style="margin-bottom:20px">
    <h3>{name}</h3>

    <div style="display:flex;gap:10px">

    <div style="width:40px;height:40px;background:{p['primary']}"></div>
    <div style="width:40px;height:40px;background:{p['secondary']}"></div>
    <div style="width:40px;height:40px;background:{p['background']}"></div>

    </div>
    </div>
    """


# ------------------------------
# Guide Section
# ------------------------------

guide_html = """
<h2>How to Use HTML Quick-Styler</h2>

<ol>
<li>Select a template</li>
<li>Select color palette</li>
<li>Enter your details</li>
<li>Click Generate Website</li>
<li>Preview your website</li>
<li>Download the HTML file</li>
</ol>

<p>This tool generates modern websites using AI-generated content.</p>
"""


# ======================================
# Build Gradio App
# ======================================

with gr.Blocks(title="HTML Quick-Styler") as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler")
    gr.Markdown("Generate full websites using AI")

    with gr.Tabs():

        # ----------------------------------
        # TAB 1 — GENERATE WEBSITE
        # ----------------------------------

        with gr.Tab("Generate Code"):

            template_dropdown = gr.Dropdown(
                template_engine.list_templates(),
                label="Select Template"
            )

            palette_dropdown = gr.Dropdown(
                palette_engine.list_palettes(),
                label="Select Color Palette",
                value="modern"
            )

            name_input = gr.Textbox(label="Main Name / Title")

            about_input = gr.Textbox(label="About")

            field3 = gr.Textbox(label="Field 3")

            field4 = gr.Textbox(label="Field 4")

            field5 = gr.Textbox(label="Field 5")

            generate_btn = gr.Button("Generate Website")

            html_output = gr.Code(
                label="Generated HTML Code",
                language="html"
            )

            download_file = gr.File(label="Download HTML File")


        # ----------------------------------
        # TAB 2 — LIVE PREVIEW
        # ----------------------------------

        with gr.Tab("Live Preview"):

            preview_html = gr.HTML()


        # ----------------------------------
        # TAB 3 — COLOR PALETTES
        # ----------------------------------

        with gr.Tab("Color Palettes"):

            gr.HTML(palette_html)


        # ----------------------------------
        # TAB 4 — TEMPLATES
        # ----------------------------------

        with gr.Tab("Templates"):

            gr.HTML(templates_html)


        # ----------------------------------
        # TAB 5 — GUIDE
        # ----------------------------------

        with gr.Tab("Guide"):

            gr.HTML(guide_html)


    # ----------------------------------
    # BUTTON ACTION
    # ----------------------------------

    generate_btn.click(
        fn=ui_generate,
        inputs=[
            template_dropdown,
            palette_dropdown,
            name_input,
            about_input,
            field3,
            field4,
            field5
        ],
        outputs=[
            html_output,
            preview_html,
            download_file
        ]
    )


demo.launch()