# -*- coding: utf-8 -*-
"""htmlgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7GOu3WoL1hXvZcKo_0AOgUfdfyk7mNJ

Install Dependencies
"""

# Install Gradio UI framework
!pip install -q gradio

# Install HuggingFace Transformers for AI models
!pip install -q transformers

# Install Accelerate for optimized model loading
!pip install -q accelerate

# Install PyTorch (Deep Learning backend)
!pip install -q torch

# Install HuggingFace Hub for downloading models
!pip install -q huggingface_hub

print("✅ All dependencies installed successfully!")

"""Import Libraries"""

# Import Gradio for UI
import gradio as gr

# Import PyTorch for model execution
import torch

# Import HuggingFace transformers
from transformers import AutoTokenizer, AutoModelForCausalLM

# Utility libraries
import os
import json

print("✅ Libraries imported successfully!")

"""Load IBM Granite Model"""

MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"

print("⏳ Loading IBM Granite Model... This may take a minute.")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

print("✅ IBM Granite model loaded successfully!")

"""AI HTML Generator"""

def generate_ai_html(prompt):
    """
    Generate HTML content using IBM Granite model
    """

    # Tokenize prompt
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # Generate output
    outputs = model.generate(
        **inputs,
        max_new_tokens=600,
        temperature=0.4,
        top_p=0.9,
        do_sample=True
    )

    # Decode result
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return generated_text

"""Color Palette Generator"""

class ColorPaletteGenerator:
    """
    Provides predefined color palettes for website generation
    """

    def __init__(self):

        self.palettes = {

            "modern": {
                "primary": "#2563EB",
                "secondary": "#4F46E5",
                "accent": "#22C55E",
                "background": "#F8FAFC",
                "surface": "#FFFFFF",
                "text_primary": "#111827",
                "text_secondary": "#6B7280",
                "border": "#E5E7EB"
            },

            "vibrant": {
                "primary": "#FF3B3B",
                "secondary": "#FF8C00",
                "accent": "#FFD700",
                "background": "#FFF7ED",
                "surface": "#FFFFFF",
                "text_primary": "#1F2937",
                "text_secondary": "#6B7280",
                "border": "#F59E0B"
            },

            "ocean": {
                "primary": "#0284C7",
                "secondary": "#0369A1",
                "accent": "#22D3EE",
                "background": "#F0F9FF",
                "surface": "#FFFFFF",
                "text_primary": "#0F172A",
                "text_secondary": "#475569",
                "border": "#BAE6FD"
            },

            "forest": {
                "primary": "#166534",
                "secondary": "#15803D",
                "accent": "#4ADE80",
                "background": "#F0FDF4",
                "surface": "#FFFFFF",
                "text_primary": "#052E16",
                "text_secondary": "#4B5563",
                "border": "#BBF7D0"
            },

            "sunset": {
                "primary": "#F97316",
                "secondary": "#FB923C",
                "accent": "#F43F5E",
                "background": "#FFF7ED",
                "surface": "#FFFFFF",
                "text_primary": "#1F2937",
                "text_secondary": "#6B7280",
                "border": "#FED7AA"
            },

            "luxury": {
                "primary": "#111827",
                "secondary": "#374151",
                "accent": "#D4AF37",
                "background": "#F9FAFB",
                "surface": "#FFFFFF",
                "text_primary": "#111827",
                "text_secondary": "#6B7280",
                "border": "#E5E7EB"
            },

            "creative": {
                "primary": "#7C3AED",
                "secondary": "#9333EA",
                "accent": "#F472B6",
                "background": "#FAF5FF",
                "surface": "#FFFFFF",
                "text_primary": "#1F2937",
                "text_secondary": "#6B7280",
                "border": "#E9D5FF"
            },

            "minimal": {
                "primary": "#111111",
                "secondary": "#444444",
                "accent": "#888888",
                "background": "#FFFFFF",
                "surface": "#F5F5F5",
                "text_primary": "#111111",
                "text_secondary": "#666666",
                "border": "#DDDDDD"
            }

        }

    def get_palette(self, name):
        """
        Return selected palette
        """
        return self.palettes.get(name, self.palettes["modern"])

    def list_palettes(self):
        """
        Return all palette names
        """
        return list(self.palettes.keys())


# Create palette generator instance
palette_generator = ColorPaletteGenerator()

print("🎨 Color Palette Generator Ready!")
print("Available Palettes:", palette_generator.list_palettes())

"""HTML Page Builder"""

class HTMLPageBuilder:
    """
    Responsible for building the HTML structure of the website
    """

    def __init__(self):
        self.available_sections = [
            "hero",
            "features",
            "about",
            "portfolio",
            "testimonials",
            "pricing",
            "contact",
            "footer"
        ]


    # ------------------------------------------------------
    # Detect sections based on description keywords
    # ------------------------------------------------------
    def detect_sections(self, description):

        description = description.lower()
        detected = []

        for section in self.available_sections:
            if section in description:
                detected.append(section)

        # Ensure footer always exists
        if "footer" not in detected:
            detected.append("footer")

        return detected


    # ------------------------------------------------------
    # Generate SEO Meta Tags
    # ------------------------------------------------------
    def generate_meta_tags(self, title, description):

        meta = f"""
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="{description}">
<meta name="keywords" content="website, portfolio, modern site">
<meta name="author" content="HTML Quick Styler AI">
<title>{title}</title>
"""
        return meta


    # ------------------------------------------------------
    # Generate HTML for each section
    # ------------------------------------------------------
    def generate_section_html(self, section, title):

        if section == "hero":
            return f"""
<section class="hero">
<div class="container">
<h1>Welcome to {title}</h1>
<p>We create beautiful and modern web experiences.</p>
<button class="btn-primary">Get Started</button>
</div>
</section>
"""

        elif section == "features":
            return """
<section class="features">
<div class="container">
<h2>Features</h2>

<div class="feature-grid">

<div class="card">
<h3>Fast</h3>
<p>Lightning fast performance.</p>
</div>

<div class="card">
<h3>Responsive</h3>
<p>Works on all devices.</p>
</div>

<div class="card">
<h3>Modern</h3>
<p>Clean modern design.</p>
</div>

</div>
</div>
</section>
"""

        elif section == "about":
            return """
<section class="about">
<div class="container">
<h2>About Us</h2>
<p>We are passionate about building amazing digital products and experiences.</p>
</div>
</section>
"""

        elif section == "portfolio":
            return """
<section class="portfolio">
<div class="container">
<h2>Portfolio</h2>

<div class="portfolio-grid">
<div class="card">Project 1</div>
<div class="card">Project 2</div>
<div class="card">Project 3</div>
</div>

</div>
</section>
"""

        elif section == "testimonials":
            return """
<section class="testimonials">
<div class="container">
<h2>Testimonials</h2>

<div class="card">
<p>"Amazing service and beautiful design!"</p>
</div>

</div>
</section>
"""

        elif section == "pricing":
            return """
<section class="pricing">
<div class="container">
<h2>Pricing</h2>

<div class="pricing-grid">

<div class="card">
<h3>Basic</h3>
<p>$9/month</p>
</div>

<div class="card">
<h3>Pro</h3>
<p>$29/month</p>
</div>

</div>
</div>
</section>
"""

        elif section == "contact":
            return """
<section class="contact">
<div class="container">
<h2>Contact Us</h2>

<form>
<input type="text" placeholder="Name">
<input type="email" placeholder="Email">
<textarea placeholder="Message"></textarea>
<button type="submit">Send</button>
</form>

</div>
</section>
"""

        elif section == "footer":
            return """
<footer>
<div class="container">
<p>© 2026 HTML Quick-Styler. All rights reserved.</p>
</div>
</footer>
"""

        return ""


    # ------------------------------------------------------
    # Build full HTML structure
    # ------------------------------------------------------
    def build_full_page(self, title, description):

        sections = self.detect_sections(description)

        html_sections = ""

        for sec in sections:
            html_sections += self.generate_section_html(sec, title)

        meta_tags = self.generate_meta_tags(title, description)

        html_page = f"""
<!DOCTYPE html>
<html lang="en">

<head>
{meta_tags}
<link rel="stylesheet" href="styles.css">
</head>

<body>

{html_sections}

</body>
</html>
"""

        return html_page


# Create builder instance
html_builder = HTMLPageBuilder()

print("🌐 HTML Page Builder Ready!")

"""CSS Generator"""

# ==========================================================
# HTML Quick-Styler Project
# SECTION 6 — CSS Generator
# ==========================================================

def generate_css(palette):
    """
    Generate modern CSS styling based on the selected palette
    """

    css = f"""
/* ============================
CSS VARIABLES
============================ */

:root {{
--primary: {palette['primary']};
--secondary: {palette['secondary']};
--accent: {palette['accent']};
--background: {palette['background']};
--surface: {palette['surface']};
--text-primary: {palette['text_primary']};
--text-secondary: {palette['text_secondary']};
--border: {palette['border']};
}}


/* ============================
GLOBAL STYLES
============================ */

* {{
margin: 0;
padding: 0;
box-sizing: border-box;
font-family: 'Segoe UI', sans-serif;
}}

body {{
background: var(--background);
color: var(--text-primary);
line-height: 1.6;
}}

.container {{
width: 90%;
max-width: 1100px;
margin: auto;
padding: 40px 0;
}}


/* ============================
HERO SECTION
============================ */

.hero {{
background: linear-gradient(135deg, var(--primary), var(--secondary));
color: white;
text-align: center;
padding: 120px 20px;
}}

.hero h1 {{
font-size: 48px;
margin-bottom: 20px;
}}

.hero p {{
font-size: 20px;
margin-bottom: 30px;
}}

.btn-primary {{
background: var(--accent);
color: white;
border: none;
padding: 12px 25px;
border-radius: 8px;
cursor: pointer;
transition: 0.3s;
}}

.btn-primary:hover {{
transform: scale(1.05);
}}


/* ============================
FEATURE GRID
============================ */

.feature-grid {{
display: grid;
grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
gap: 20px;
margin-top: 30px;
}}

.card {{
background: rgba(255,255,255,0.6);
backdrop-filter: blur(10px);
padding: 25px;
border-radius: 12px;
border: 1px solid var(--border);
transition: 0.3s;
}}

.card:hover {{
transform: translateY(-8px);
box-shadow: 0 10px 25px rgba(0,0,0,0.1);
}}


/* ============================
PORTFOLIO GRID
============================ */

.portfolio-grid {{
display: grid;
grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
gap: 20px;
margin-top: 30px;
}}

.portfolio-grid .card {{
text-align: center;
font-weight: bold;
}}


/* ============================
CONTACT FORM
============================ */

form {{
display: flex;
flex-direction: column;
gap: 10px;
margin-top: 20px;
}}

input, textarea {{
padding: 10px;
border-radius: 6px;
border: 1px solid var(--border);
}}

button {{
background: var(--primary);
color: white;
padding: 10px;
border: none;
border-radius: 6px;
cursor: pointer;
}}

button:hover {{
background: var(--secondary);
}}


/* ============================
FOOTER
============================ */

footer {{
background: var(--primary);
color: white;
text-align: center;
padding: 20px;
margin-top: 40px;
}}


/* ============================
RESPONSIVE DESIGN
============================ */

@media (max-width: 768px) {{

.hero h1 {{
font-size: 32px;
}}

.hero p {{
font-size: 16px;
}}

.container {{
width: 95%;
}}

}}

"""
    return css


print("🎨 CSS Generator Ready!")

"""Website Generator Pipeline"""

# ==========================================================
# HTML Quick-Styler Project
# SECTION 7 — Website Generator Pipeline
# ==========================================================

def generate_website(title, description, palette_name):
    """
    Main pipeline that generates the full website
    """

    # 1️⃣ Get selected color palette
    palette = palette_generator.get_palette(palette_name)

    # 2️⃣ Generate CSS using palette
    css = generate_css(palette)

    # 3️⃣ Generate HTML structure using builder
    html_structure = html_builder.build_full_page(title, description)

    # 4️⃣ Generate AI content using Granite
    ai_prompt = f"""
Create modern website content for a page.

Title: {title}

Description:
{description}

Write short professional website text content for sections like
hero, features, about, testimonials and contact.
"""

    ai_content = generate_ai_html(ai_prompt)

    # 5️⃣ Combine CSS and HTML into a single document
    final_html = html_structure.replace(
        '<link rel="stylesheet" href="styles.css">',
        f"<style>\n{css}\n</style>"
    )

    # 6️⃣ Insert AI content comment (optional for future expansion)
    final_html += f"\n<!-- AI Generated Content -->\n<!-- {ai_content[:500]} -->"

    # 7️⃣ Save HTML file
    file_path = "generated_website.html"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(final_html)

    return final_html, file_path


print("🚀 Website Generator Pipeline Ready!")

"""Gradio Interface"""

# ==========================================================
# HTML Quick-Styler Project
# SECTION 8 — Gradio Interface
# ==========================================================

import gradio as gr


# Function to handle UI generation
def ui_generate(title, description, palette):

    html, file_path = generate_website(title, description, palette)

    return html, html, file_path


# ---------------------------------------
# Palette Display Function
# ---------------------------------------

def show_palettes():

    html = ""

    for name in palette_generator.list_palettes():

        p = palette_generator.get_palette(name)

        html += f"""
        <div style="margin-bottom:20px;padding:15px;border:1px solid #ddd;border-radius:10px">
        <h3>{name.title()} Palette</h3>

        <div style="display:flex;gap:10px">

        <div style="width:40px;height:40px;background:{p['primary']}"></div>
        <div style="width:40px;height:40px;background:{p['secondary']}"></div>
        <div style="width:40px;height:40px;background:{p['accent']}"></div>
        <div style="width:40px;height:40px;background:{p['background']}"></div>
        <div style="width:40px;height:40px;background:{p['surface']}"></div>

        </div>
        </div>
        """

    return html


# ---------------------------------------
# Example Templates
# ---------------------------------------

templates_html = """
<h2>Example Website Ideas</h2>

<ul>
<li>Startup Landing Page</li>
<li>Portfolio Website</li>
<li>Restaurant Website</li>
<li>AI SaaS Product Page</li>
<li>Personal Blog</li>
<li>Photography Portfolio</li>
</ul>
"""


# ---------------------------------------
# Guide Section
# ---------------------------------------

guide_html = """
<h2>How to Use HTML Quick-Styler</h2>

<ol>
<li>Enter your website title</li>
<li>Describe the page layout</li>
<li>Select a color palette</li>
<li>Click Generate Website</li>
<li>Preview the page</li>
<li>Download the HTML file</li>
</ol>

<p>This tool generates responsive websites using AI.</p>
"""


# ==========================================================
# Build Gradio UI
# ==========================================================

with gr.Blocks(title="HTML Quick-Styler") as demo:

    gr.Markdown("# 🚀 HTML Quick-Styler")
    gr.Markdown("Generate complete modern websites using AI.")

    with gr.Tabs():

        # ====================================
        # TAB 1 — GENERATE PAGE
        # ====================================

        with gr.Tab("Generate Page"):

            title_input = gr.Textbox(label="Page Title")

            description_input = gr.Textbox(
                label="Page Description",
                lines=6
            )

            palette_dropdown = gr.Dropdown(
                palette_generator.list_palettes(),
                label="Color Palette",
                value="modern"
            )

            generate_btn = gr.Button("Generate Website")

            html_output = gr.Code(
                label="Generated HTML Code",
                language="html"
            )

            download_file = gr.File(label="Download HTML File")


        # ====================================
        # TAB 2 — LIVE PREVIEW
        # ====================================

        with gr.Tab("Live Preview"):

            preview_html = gr.HTML()


        # ====================================
        # TAB 3 — COLOR PALETTES
        # ====================================

        with gr.Tab("Color Palettes"):

            gr.HTML(show_palettes())


        # ====================================
        # TAB 4 — TEMPLATES
        # ====================================

        with gr.Tab("Templates"):

            gr.HTML(templates_html)


        # ====================================
        # TAB 5 — GUIDE
        # ====================================

        with gr.Tab("Guide"):

            gr.HTML(guide_html)


    # ====================================
    # BUTTON ACTION
    # ====================================

    generate_btn.click(
        fn=ui_generate,
        inputs=[title_input, description_input, palette_dropdown],
        outputs=[html_output, preview_html, download_file]
    )


print("🎨 Gradio UI Ready!")

"""Launch Application"""

print("🚀 Launching HTML Quick-Styler Web App...")

demo.launch(
    share=True,   # Creates public Gradio link
    debug=True
)